packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@hey-api/client-fetch': ^0.13.1
  '@hey-api/openapi-ts': 0.94.4
  "@types/node": ^24
  react-grab: ^0.1.28
  react-hook-form: ^7.71.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@0.1.12
  vite-plus: 0.1.12
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.12

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
