packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@hey-api/client-fetch": ^0.13.1
  "@hey-api/openapi-ts": 0.94.4
  "@types/node": ^24
  "@types/react-big-calendar": ^1.16.3
  date-fns: ^4.1.0
  execa: ^9.6.1
  jspdf: ^4.2.1
  jspdf-autotable: ^5.0.7
  lucide-react: ^0.577.0
  react-big-calendar: ^1.19.4
  react-grab: ^0.1.28
  react-hook-form: ^7.71.2
  sonner: ^2.0.7
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@0.1.12
  vite-plugin-pwa: ^1.2.0
  vite-plus: 0.1.12
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.12
  workbox-background-sync: ^7.4.0
  workbox-core: ^7.4.0
  workbox-expiration: ^7.4.0
  workbox-precaching: ^7.4.0
  workbox-routing: ^7.4.0
  workbox-strategies: ^7.4.0

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
