-- OpenToggl PostgreSQL desired-state schema.

create table identity_users (
    id bigserial primary key,
    email text not null unique,
    full_name text not null,
    password_hash text not null,
    api_token text not null unique,
    timezone text not null default 'UTC',
    beginning_of_week integer not null default 0,
    country_id bigint not null default 0,
    default_workspace_id bigint not null default 0,
    state text not null,
    preferences_date_format text not null default 'YYYY-MM-DD',
    preferences_time_of_day_format text not null default 'h:mm A',
    preferences_alpha_features jsonb not null default '[]'::jsonb,
    constraint identity_users_state_check check (state in ('active', 'deactivated', 'deleted'))
);

create table identity_sessions (
    id text primary key,
    user_id bigint not null references identity_users (id) on delete cascade,
    created_at timestamptz not null default now()
);

create table identity_job_records (
    id bigint generated by default as identity primary key,
    job_name text not null,
    user_id bigint not null references identity_users (id) on delete cascade,
    created_at timestamptz not null default now()
);

create index identity_job_records_user_id_idx on identity_job_records (user_id);

create table tracking_running_timers (
    user_id bigint primary key references identity_users (id) on delete cascade,
    started_at timestamptz not null default now()
);

create table tenant_organizations (
    id bigint generated by default as identity primary key,
    name text not null
);

create table tenant_workspaces (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references tenant_organizations (id) on delete cascade,
    name text not null,
    logo_storage_key text not null default '',
    avatar_storage_key text not null default '',
    default_currency text not null default 'USD',
    default_hourly_rate double precision not null default 0,
    rounding integer not null default 0,
    rounding_minutes integer not null default 0,
    display_policy text not null default 'standard',
    only_admins_may_create_projects boolean not null default false,
    only_admins_may_create_tags boolean not null default false,
    only_admins_see_team_dashboard boolean not null default false,
    projects_billable_by_default boolean not null default false,
    projects_private_by_default boolean not null default false,
    projects_enforce_billable boolean not null default false,
    reports_collapse boolean not null default false,
    public_project_access text not null default 'members',
    report_locked_at text not null default '',
    show_timesheet_view boolean not null default true,
    required_time_entry_fields jsonb not null default '[]'::jsonb,
    constraint tenant_workspaces_display_policy_check check (display_policy in ('standard', 'hide_start_end_times')),
    constraint tenant_workspaces_public_project_access_check check (public_project_access in ('members', 'admins'))
);

create index tenant_workspaces_organization_id_idx on tenant_workspaces (organization_id);

create table billing_accounts (
    organization_id bigint primary key references tenant_organizations (id) on delete cascade,
    customer_id text not null default '',
    subscription_plan text not null,
    subscription_state text not null,
    quota_remaining integer not null default 0,
    quota_resets_in_secs integer not null default 0,
    quota_total integer not null default 0
);

create table web_user_homes (
    user_id bigint primary key references identity_users (id) on delete cascade,
    organization_id bigint not null references tenant_organizations (id) on delete cascade,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade
);

create table catalog_clients (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    name text not null,
    archived boolean not null default false,
    created_by bigint references identity_users (id) on delete set null,
    created_at timestamptz not null default now()
);

create index catalog_clients_workspace_id_idx on catalog_clients (workspace_id);
create unique index catalog_clients_workspace_name_key on catalog_clients (workspace_id, lower(name));

create table catalog_projects (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    client_id bigint references catalog_clients (id) on delete set null,
    name text not null,
    active boolean not null default true,
    pinned boolean not null default false,
    template boolean not null default false,
    actual_seconds bigint not null default 0,
    recurring boolean not null default false,
    recurring_period_start date,
    recurring_period_end date,
    created_by bigint references identity_users (id) on delete set null,
    created_at timestamptz not null default now()
);

create index catalog_projects_workspace_id_idx on catalog_projects (workspace_id);
create index catalog_projects_client_id_idx on catalog_projects (client_id);
create unique index catalog_projects_workspace_name_key on catalog_projects (workspace_id, lower(name));

create table catalog_project_users (
    project_id bigint not null references catalog_projects (id) on delete cascade,
    user_id bigint not null references identity_users (id) on delete cascade,
    role text not null default 'member',
    created_at timestamptz not null default now(),
    primary key (project_id, user_id),
    constraint catalog_project_users_role_check check (role in ('admin', 'member'))
);

create index catalog_project_users_user_id_idx on catalog_project_users (user_id);

create table catalog_groups (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    name text not null,
    has_users boolean not null default false,
    created_by bigint references identity_users (id) on delete set null,
    created_at timestamptz not null default now()
);

create index catalog_groups_workspace_id_idx on catalog_groups (workspace_id);
create unique index catalog_groups_workspace_name_key on catalog_groups (workspace_id, lower(name));

create table catalog_tags (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    name text not null,
    deleted_at timestamptz,
    created_by bigint references identity_users (id) on delete set null,
    created_at timestamptz not null default now()
);

create index catalog_tags_workspace_id_idx on catalog_tags (workspace_id);
create unique index catalog_tags_workspace_name_key on catalog_tags (workspace_id, lower(name));

create table catalog_tasks (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    project_id bigint references catalog_projects (id) on delete set null,
    name text not null,
    active boolean not null default true,
    created_by bigint references identity_users (id) on delete set null,
    created_at timestamptz not null default now()
);

create index catalog_tasks_workspace_id_idx on catalog_tasks (workspace_id);
create index catalog_tasks_project_id_idx on catalog_tasks (project_id);
create unique index catalog_tasks_workspace_name_key on catalog_tasks (workspace_id, lower(name));
