-- OpenToggl PostgreSQL desired-state schema.

create table identity_users (
    id bigserial primary key,
    email text not null unique,
    full_name text not null,
    password_hash text not null,
    api_token text not null unique,
    timezone text not null default 'UTC',
    beginning_of_week integer not null default 0,
    country_id bigint not null default 0,
    default_workspace_id bigint not null default 0,
    state text not null,
    preferences_date_format text not null default 'YYYY-MM-DD',
    preferences_time_of_day_format text not null default 'h:mm A',
    preferences_alpha_features jsonb not null default '[]'::jsonb,
    constraint identity_users_state_check check (state in ('active', 'deactivated', 'deleted'))
);

create table identity_sessions (
    id text primary key,
    user_id bigint not null references identity_users (id) on delete cascade,
    created_at timestamptz not null default now()
);

create table identity_job_records (
    id bigint generated by default as identity primary key,
    job_name text not null,
    user_id bigint not null references identity_users (id) on delete cascade,
    created_at timestamptz not null default now()
);

create index identity_job_records_user_id_idx on identity_job_records (user_id);

create table tracking_running_timers (
    user_id bigint primary key references identity_users (id) on delete cascade,
    started_at timestamptz not null default now()
);

create table tenant_organizations (
    id bigint generated by default as identity primary key,
    name text not null
);

create table tenant_workspaces (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references tenant_organizations (id) on delete cascade,
    name text not null,
    logo_storage_key text not null default '',
    avatar_storage_key text not null default '',
    default_currency text not null default 'USD',
    default_hourly_rate double precision not null default 0,
    rounding integer not null default 0,
    rounding_minutes integer not null default 0,
    display_policy text not null default 'standard',
    only_admins_may_create_projects boolean not null default false,
    only_admins_may_create_tags boolean not null default false,
    only_admins_see_team_dashboard boolean not null default false,
    projects_billable_by_default boolean not null default false,
    projects_private_by_default boolean not null default false,
    projects_enforce_billable boolean not null default false,
    reports_collapse boolean not null default false,
    public_project_access text not null default 'members',
    report_locked_at text not null default '',
    show_timesheet_view boolean not null default true,
    required_time_entry_fields jsonb not null default '[]'::jsonb,
    constraint tenant_workspaces_display_policy_check check (display_policy in ('standard', 'hide_start_end_times')),
    constraint tenant_workspaces_public_project_access_check check (public_project_access in ('members', 'admins'))
);

create index tenant_workspaces_organization_id_idx on tenant_workspaces (organization_id);

create table billing_accounts (
    organization_id bigint primary key references tenant_organizations (id) on delete cascade,
    customer_id text not null default '',
    subscription_plan text not null,
    subscription_state text not null,
    quota_remaining integer not null default 0,
    quota_resets_in_secs integer not null default 0,
    quota_total integer not null default 0
);

create table web_user_homes (
    user_id bigint primary key references identity_users (id) on delete cascade,
    organization_id bigint not null references tenant_organizations (id) on delete cascade,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade
);
