import { z } from "zod";

// Semver-ish: accepts "1.2.3", "1.2.3-rc.1", "dev". Kept permissive because
// self-hosters may run patched/forked builds.
const versionString = z
  .string()
  .min(1)
  .max(64)
  .regex(/^[A-Za-z0-9._+-]+$/, "invalid version characters");

const shortToken = z
  .string()
  .min(1)
  .max(32)
  .regex(/^[A-Za-z0-9._+\-/]+$/, "invalid token characters");

export const checkRequestSchema = z.object({
  // Stable per-instance UUID, generated by the backend on first boot.
  instanceId: z.string().uuid(),
  version: versionString,
  goVersion: shortToken.optional(),
  os: shortToken.optional(),
  arch: shortToken.optional(),
  locale: shortToken.optional(),
});

export type CheckRequestInput = z.infer<typeof checkRequestSchema>;
