-- +goose Up
-- Tables added between v0.0.17 and main that are missing from a v0.0.17
-- database after bridging the baseline.

create table if not exists membership_organization_members (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references tenant_organizations (id) on delete cascade,
    user_id bigint not null references identity_users (id) on delete cascade,
    role text not null default 'member',
    state text not null default 'joined',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint membership_organization_members_role_check check (role in ('owner', 'admin', 'member')),
    constraint membership_organization_members_state_check check (state in ('joined', 'inactive'))
);

create unique index if not exists membership_organization_members_org_user_key on membership_organization_members (organization_id, user_id);
create index if not exists membership_organization_members_user_id_idx on membership_organization_members (user_id);

create table if not exists catalog_group_members (
    group_id bigint not null references catalog_groups (id) on delete cascade,
    user_id bigint not null references identity_users (id) on delete cascade,
    primary key (group_id, user_id)
);

create index if not exists catalog_group_members_user_id_idx on catalog_group_members (user_id);

create table if not exists catalog_group_workspaces (
    group_id bigint not null references catalog_groups (id) on delete cascade,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    primary key (group_id, workspace_id)
);

create index if not exists catalog_group_workspaces_workspace_id_idx on catalog_group_workspaces (workspace_id);

create table if not exists saved_reports (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    name text not null default '',
    public boolean not null default false,
    fixed_date_range boolean not null default false,
    token text,
    params jsonb not null default '{}',
    created_by bigint not null references identity_users (id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    deleted_at timestamptz
);

create index if not exists saved_reports_workspace_id_idx on saved_reports (workspace_id);
create unique index if not exists saved_reports_token_idx on saved_reports (token) where token is not null;

create table if not exists scheduled_reports (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null references tenant_workspaces (id) on delete cascade,
    report_id bigint not null references saved_reports (id) on delete cascade,
    frequency int not null default 1,
    creator_id bigint not null references identity_users (id),
    user_ids bigint[] not null default '{}',
    group_ids bigint[] not null default '{}',
    created_at timestamptz not null default now(),
    deleted_at timestamptz
);

-- +goose Down
drop table if exists scheduled_reports;
drop table if exists saved_reports;
drop table if exists catalog_group_workspaces;
drop table if exists catalog_group_members;
drop table if exists membership_organization_members;
