import { rootRoute } from "./root-route.tsx";
import {
  protectedLayoutRoute,
  homeRoute,
  loginRoute,
  registerRoute,
  inviteStatusJoinedRoute,
  accountRoute,
  profileRoute,
} from "./route-tree-auth.tsx";
import {
  workspaceOverviewRoute,
  workspaceTimerStartRoute,
  workspaceTimerRoute,
  workspaceReportsRoute,
  legacyWorkspaceReportsRoute,
  workspaceProjectsRoute,
  workspaceProjectDetailRoute,
  projectDashboardRoute,
  legacyWorkspaceProjectsRoute,
  legacyWorkspaceProjectDetailRoute,
  workspaceMembersRoute,
  workspaceImportRoute,
  legacyWorkspaceImportRoute,
} from "./route-tree-workspace.tsx";
import {
  workspaceClientsRoute,
  workspaceClientDetailRoute,
  workspaceGroupsRoute,
  workspacePermissionsRoute,
  projectTasksRoute,
  legacyWorkspaceTasksRoute,
  workspaceTagsRoute,
  workspaceTagDetailRoute,
  workspaceApprovalsRoute,
  legacyWorkspaceApprovalsRoute,
  workspaceInvoiceNewRoute,
  workspaceInvoicesRoute,
  workspaceGoalsRoute,
  workspaceIntegrationsRoute,
  workspaceAuditLogRoute,
  workspaceSubscriptionRoute,
} from "./route-tree-manage.tsx";
import {
  workspaceSettingsRoute,
  legacyWorkspaceSettingsRoute,
  organizationSettingsRoute,
  legacyOrganizationSettingsRoute,
  instanceAdminRoute,
} from "./route-tree-settings.tsx";
import {
  mobileLayoutRoute,
  mobileIndexRoute,
  mobileTimerRoute,
  mobileCalendarRoute,
  mobileReportRoute,
  mobileMeRoute,
} from "./route-tree-mobile.tsx";

export const routeTree = rootRoute.addChildren([
  loginRoute,
  registerRoute,
  inviteStatusJoinedRoute,
  protectedLayoutRoute.addChildren([
    homeRoute,
    accountRoute,
    profileRoute,
    workspaceOverviewRoute,
    workspaceTimerStartRoute,
    workspaceTimerRoute,
    workspaceReportsRoute,
    legacyWorkspaceReportsRoute,
    workspaceProjectsRoute,
    workspaceProjectDetailRoute,
    projectDashboardRoute,
    legacyWorkspaceProjectsRoute,
    legacyWorkspaceProjectDetailRoute,
    workspaceMembersRoute,
    workspaceImportRoute,
    legacyWorkspaceImportRoute,
    workspaceClientsRoute,
    workspaceClientDetailRoute,
    workspaceGroupsRoute,
    workspacePermissionsRoute,
    projectTasksRoute,
    legacyWorkspaceTasksRoute,
    workspaceTagsRoute,
    workspaceTagDetailRoute,
    workspaceApprovalsRoute,
    legacyWorkspaceApprovalsRoute,
    workspaceInvoiceNewRoute,
    workspaceInvoicesRoute,
    workspaceGoalsRoute,
    workspaceIntegrationsRoute,
    workspaceAuditLogRoute,
    workspaceSubscriptionRoute,
    workspaceSettingsRoute,
    legacyWorkspaceSettingsRoute,
    organizationSettingsRoute,
    legacyOrganizationSettingsRoute,
    instanceAdminRoute,
  ]),
  mobileLayoutRoute.addChildren([
    mobileIndexRoute,
    mobileTimerRoute,
    mobileCalendarRoute,
    mobileReportRoute,
    mobileMeRoute,
  ]),
]);
