// Reads content/changelog/*.md and content/announcements/*.md, parses YAML
// frontmatter, and emits src/content.generated.ts — a typed module the worker
// imports at build time. Run this before `tsc` / `wrangler dev` / `wrangler deploy`.

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname, basename, extname } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const contentDir = join(root, "content");
const outFile = join(root, "src", "content.generated.ts");

async function listMarkdown(dir) {
  try {
    const entries = await readdir(dir);
    return entries
      .filter((name) => name.endsWith(".md"))
      .map((name) => join(dir, name))
      .sort();
  } catch (err) {
    if (err && err.code === "ENOENT") return [];
    throw err;
  }
}

async function parseChangelog(path) {
  const raw = await readFile(path, "utf8");
  const { data, content } = matter(raw);
  const tag = String(data.tag ?? basename(path, extname(path)));
  if (!data.date) throw new Error(`changelog ${path} missing 'date' frontmatter`);
  return {
    tag,
    date: String(data.date),
    title: data.title ? String(data.title) : tag,
    bodyMarkdown: content.trim(),
  };
}

async function parseAnnouncement(path) {
  const raw = await readFile(path, "utf8");
  const { data, content } = matter(raw);
  const id = String(data.id ?? basename(path, extname(path)));
  if (!data.publishedAt) throw new Error(`announcement ${path} missing 'publishedAt' frontmatter`);
  if (!data.title) throw new Error(`announcement ${path} missing 'title' frontmatter`);
  const severity = data.severity ?? "info";
  if (!["info", "warning", "critical"].includes(severity)) {
    throw new Error(`announcement ${path} invalid 'severity' (got ${severity})`);
  }
  return {
    id,
    title: String(data.title),
    severity,
    publishedAt: String(data.publishedAt),
    expiresAt: data.expiresAt ? String(data.expiresAt) : null,
    link: data.link ? String(data.link) : null,
    bodyMarkdown: content.trim(),
  };
}

function byDateDesc(a, b) {
  return b.date.localeCompare(a.date);
}

function byPublishedDesc(a, b) {
  return b.publishedAt.localeCompare(a.publishedAt);
}

async function main() {
  const changelogPaths = await listMarkdown(join(contentDir, "changelog"));
  const announcementPaths = await listMarkdown(join(contentDir, "announcements"));

  const changelog = (await Promise.all(changelogPaths.map(parseChangelog))).sort(byDateDesc);
  const announcements = (await Promise.all(announcementPaths.map(parseAnnouncement))).sort(
    byPublishedDesc,
  );

  const banner = [
    "// AUTO-GENERATED by scripts/build-content.mjs. Do not edit by hand.",
    "// Regenerate: `vp run update-worker#build:content`",
    "",
    'import type { ChangelogEntry, Announcement } from "./types.ts";',
    "",
  ].join("\n");

  const body = [
    `export const generatedChangelog: ChangelogEntry[] = ${JSON.stringify(changelog, null, 2)};`,
    "",
    `export const generatedAnnouncements: Announcement[] = ${JSON.stringify(
      announcements,
      null,
      2,
    )};`,
    "",
  ].join("\n");

  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, banner + body, "utf8");

  console.log(
    `[update-worker] wrote ${outFile} (${changelog.length} changelog, ${announcements.length} announcements)`,
  );
}

main().catch((err) => {
  console.error("[update-worker] build-content failed:", err);
  process.exit(1);
});
