// Reads content/announcements/*.md, parses YAML frontmatter, and emits
// src/content.generated.ts — a typed module the worker imports at build time.
// Run this before `tsc` / `wrangler dev` / `wrangler deploy`.
//
// Changelog is NOT baked in: the worker sources that live from GitHub Releases.

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname, basename, extname } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const contentDir = join(root, "content");
const outFile = join(root, "src", "content.generated.ts");

async function listMarkdown(dir) {
  try {
    const entries = await readdir(dir);
    return entries
      .filter((name) => name.endsWith(".md"))
      .map((name) => join(dir, name))
      .sort();
  } catch (err) {
    if (err && err.code === "ENOENT") return [];
    throw err;
  }
}

async function parseAnnouncement(path) {
  const raw = await readFile(path, "utf8");
  const { data, content } = matter(raw);
  const id = String(data.id ?? basename(path, extname(path)));
  if (!data.publishedAt) throw new Error(`announcement ${path} missing 'publishedAt' frontmatter`);
  if (!data.title) throw new Error(`announcement ${path} missing 'title' frontmatter`);
  const severity = data.severity ?? "info";
  if (!["info", "warning", "critical"].includes(severity)) {
    throw new Error(`announcement ${path} invalid 'severity' (got ${severity})`);
  }
  return {
    id,
    title: String(data.title),
    severity,
    // Coerce to RFC 3339. Markdown authors typically write date-only (YYYY-MM-DD);
    // the Go backend's time.Time unmarshaller needs a full timestamp.
    publishedAt: toIsoOrThrow(data.publishedAt, `announcement ${path} publishedAt`),
    expiresAt: data.expiresAt
      ? toIsoOrThrow(data.expiresAt, `announcement ${path} expiresAt`)
      : null,
    link: data.link ? String(data.link) : null,
    bodyMarkdown: content.trim(),
  };
}

function toIsoOrThrow(value, label) {
  const d = new Date(String(value));
  if (Number.isNaN(d.getTime())) throw new Error(`${label}: invalid date "${value}"`);
  return d.toISOString();
}

function byPublishedDesc(a, b) {
  return b.publishedAt.localeCompare(a.publishedAt);
}

async function main() {
  const announcementPaths = await listMarkdown(join(contentDir, "announcements"));
  const announcements = (await Promise.all(announcementPaths.map(parseAnnouncement))).sort(
    byPublishedDesc,
  );

  const banner = [
    "// AUTO-GENERATED by scripts/build-content.mjs. Do not edit by hand.",
    "// Regenerate: `vp run update-worker#build:content`",
    "",
    'import type { Announcement } from "./types.ts";',
    "",
  ].join("\n");

  const body = [
    `export const generatedAnnouncements: Announcement[] = ${JSON.stringify(
      announcements,
      null,
      2,
    )};`,
    "",
  ].join("\n");

  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, banner + body, "utf8");

  console.log(`[update-worker] wrote ${outFile} (${announcements.length} announcements)`);
}

main().catch((err) => {
  console.error("[update-worker] build-content failed:", err);
  process.exit(1);
});
