// Code generated by apps/backend/scripts/generate-wave1-web-catalog-misc.mjs from openapi/opentoggl-web.openapi.json; DO NOT EDIT.

package httpapp

import (
	"context"
	"errors"
	"net/http"
	"strconv"
	"strings"

	"github.com/labstack/echo/v4"
)

var errGeneratedWebCatalogMiscBadRequest = errors.New("generated web catalog misc bad request")

type GeneratedListTasksRequest struct {
	WorkspaceID *int64 `json:"workspace_id,omitempty"`
}

type CreateTaskRequestBody struct {
	WorkspaceID int64  `json:"workspace_id"`
	Name        string `json:"name"`
}

type GeneratedListTagsRequest struct {
	WorkspaceID *int64 `json:"workspace_id,omitempty"`
}

type CreateTagRequestBody struct {
	WorkspaceID int64  `json:"workspace_id"`
	Name        string `json:"name"`
}

type GeneratedListGroupsRequest struct {
	WorkspaceID *int64 `json:"workspace_id,omitempty"`
}

type CreateGroupRequestBody struct {
	WorkspaceID int64  `json:"workspace_id"`
	Name        string `json:"name"`
}

type GeneratedWave1WebCatalogMiscHandler interface {
	ListTasks(context.Context, string, GeneratedListTasksRequest) Wave1Response
	CreateTask(context.Context, string, CreateTaskRequestBody) Wave1Response
	ListTags(context.Context, string, GeneratedListTagsRequest) Wave1Response
	CreateTag(context.Context, string, CreateTagRequestBody) Wave1Response
	ListGroups(context.Context, string, GeneratedListGroupsRequest) Wave1Response
	CreateGroup(context.Context, string, CreateGroupRequestBody) Wave1Response
}

func registerGeneratedWave1WebCatalogMiscRoutes(server *echo.Echo, handler GeneratedWave1WebCatalogMiscHandler) {
	if handler == nil {
		return
	}

	server.GET("/web/v1/tasks", func(context echo.Context) error {
		request, err := decodeGeneratedListTasksRequest(context)
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.ListTasks(context.Request().Context(), sessionID(context), request)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.POST("/web/v1/tasks", func(context echo.Context) error {
		request, err := decodeCreateTaskRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.CreateTask(context.Request().Context(), sessionID(context), request)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.GET("/web/v1/tags", func(context echo.Context) error {
		request, err := decodeGeneratedListTagsRequest(context)
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.ListTags(context.Request().Context(), sessionID(context), request)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.POST("/web/v1/tags", func(context echo.Context) error {
		request, err := decodeCreateTagRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.CreateTag(context.Request().Context(), sessionID(context), request)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.GET("/web/v1/groups", func(context echo.Context) error {
		request, err := decodeGeneratedListGroupsRequest(context)
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.ListGroups(context.Request().Context(), sessionID(context), request)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.POST("/web/v1/groups", func(context echo.Context) error {
		request, err := decodeCreateGroupRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.CreateGroup(context.Request().Context(), sessionID(context), request)
		return context.JSON(response.StatusCode, response.Body)
	})
}

func decodeGeneratedListTasksRequest(context echo.Context) (GeneratedListTasksRequest, error) {
	request := GeneratedListTasksRequest{}

	if workspaceIDValue := strings.TrimSpace(context.QueryParam("workspace_id")); workspaceIDValue != "" {
		workspaceID, err := strconv.ParseInt(workspaceIDValue, 10, 64)
		if err != nil {
			return GeneratedListTasksRequest{}, err
		}
		request.WorkspaceID = &workspaceID
	}

	return request, nil
}

func decodeCreateTaskRequest(request *http.Request) (CreateTaskRequestBody, error) {
	type createTaskRequestBodyRaw struct {
		WorkspaceID *int64  `json:"workspace_id"`
		Name        *string `json:"name"`
	}

	var raw createTaskRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return CreateTaskRequestBody{}, err
	}
	if raw.WorkspaceID == nil || raw.Name == nil {
		return CreateTaskRequestBody{}, errGeneratedWebCatalogMiscBadRequest
	}

	name := strings.TrimSpace(*raw.Name)
	if name == "" {
		return CreateTaskRequestBody{}, errGeneratedWebCatalogMiscBadRequest
	}

	return CreateTaskRequestBody{WorkspaceID: *raw.WorkspaceID, Name: name}, nil
}

func decodeGeneratedListTagsRequest(context echo.Context) (GeneratedListTagsRequest, error) {
	request := GeneratedListTagsRequest{}

	if workspaceIDValue := strings.TrimSpace(context.QueryParam("workspace_id")); workspaceIDValue != "" {
		workspaceID, err := strconv.ParseInt(workspaceIDValue, 10, 64)
		if err != nil {
			return GeneratedListTagsRequest{}, err
		}
		request.WorkspaceID = &workspaceID
	}

	return request, nil
}

func decodeCreateTagRequest(request *http.Request) (CreateTagRequestBody, error) {
	type createTagRequestBodyRaw struct {
		WorkspaceID *int64  `json:"workspace_id"`
		Name        *string `json:"name"`
	}

	var raw createTagRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return CreateTagRequestBody{}, err
	}
	if raw.WorkspaceID == nil || raw.Name == nil {
		return CreateTagRequestBody{}, errGeneratedWebCatalogMiscBadRequest
	}

	name := strings.TrimSpace(*raw.Name)
	if name == "" {
		return CreateTagRequestBody{}, errGeneratedWebCatalogMiscBadRequest
	}

	return CreateTagRequestBody{WorkspaceID: *raw.WorkspaceID, Name: name}, nil
}

func decodeGeneratedListGroupsRequest(context echo.Context) (GeneratedListGroupsRequest, error) {
	request := GeneratedListGroupsRequest{}

	if workspaceIDValue := strings.TrimSpace(context.QueryParam("workspace_id")); workspaceIDValue != "" {
		workspaceID, err := strconv.ParseInt(workspaceIDValue, 10, 64)
		if err != nil {
			return GeneratedListGroupsRequest{}, err
		}
		request.WorkspaceID = &workspaceID
	}

	return request, nil
}

func decodeCreateGroupRequest(request *http.Request) (CreateGroupRequestBody, error) {
	type createGroupRequestBodyRaw struct {
		WorkspaceID *int64  `json:"workspace_id"`
		Name        *string `json:"name"`
	}

	var raw createGroupRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return CreateGroupRequestBody{}, err
	}
	if raw.WorkspaceID == nil || raw.Name == nil {
		return CreateGroupRequestBody{}, errGeneratedWebCatalogMiscBadRequest
	}

	name := strings.TrimSpace(*raw.Name)
	if name == "" {
		return CreateGroupRequestBody{}, errGeneratedWebCatalogMiscBadRequest
	}

	return CreateGroupRequestBody{WorkspaceID: *raw.WorkspaceID, Name: name}, nil
}
