// Code generated by apps/backend/scripts/generate-wave1-web-clients.mjs from openapi/opentoggl-web.openapi.json; DO NOT EDIT.

package httpapp

import (
	"context"
	"errors"
	"net/http"
	"strconv"
	"strings"

	"github.com/labstack/echo/v4"
)

var errGeneratedWebClientsBadRequest = errors.New("generated web clients bad request")

type GeneratedListClientsRequest struct {
	WorkspaceID *int64 `json:"workspace_id,omitempty"`
}

type CreateClientRequestBody struct {
	WorkspaceID int64  `json:"workspace_id"`
	Name        string `json:"name"`
}

type GeneratedWave1WebClientsHandler interface {
	ListClients(context.Context, string, GeneratedListClientsRequest) Wave1Response
	CreateClient(context.Context, string, CreateClientRequestBody) Wave1Response
}

func registerGeneratedWave1WebClientsRoutes(
	server *echo.Echo,
	handler GeneratedWave1WebClientsHandler,
) {
	if handler == nil {
		return
	}

	server.GET("/web/v1/clients", func(context echo.Context) error {
		request, err := decodeListClientsRequest(context)
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.ListClients(context.Request().Context(), sessionID(context), request)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.POST("/web/v1/clients", func(context echo.Context) error {
		request, err := decodeCreateClientRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.CreateClient(context.Request().Context(), sessionID(context), request)
		return context.JSON(response.StatusCode, response.Body)
	})
}

func decodeListClientsRequest(context echo.Context) (GeneratedListClientsRequest, error) {
	request := GeneratedListClientsRequest{}

	if workspaceIDValue := strings.TrimSpace(context.QueryParam("workspace_id")); workspaceIDValue != "" {
		workspaceID, err := strconv.ParseInt(workspaceIDValue, 10, 64)
		if err != nil {
			return GeneratedListClientsRequest{}, err
		}
		request.WorkspaceID = &workspaceID
	}

	return request, nil
}

func decodeCreateClientRequest(request *http.Request) (CreateClientRequestBody, error) {
	type createClientRequestBodyRaw struct {
		WorkspaceID *int64  `json:"workspace_id"`
		Name        *string `json:"name"`
	}

	var raw createClientRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return CreateClientRequestBody{}, err
	}
	if raw.WorkspaceID == nil || raw.Name == nil {
		return CreateClientRequestBody{}, errGeneratedWebClientsBadRequest
	}

	name := strings.TrimSpace(*raw.Name)
	if name == "" {
		return CreateClientRequestBody{}, errGeneratedWebClientsBadRequest
	}

	return CreateClientRequestBody{
		WorkspaceID: *raw.WorkspaceID,
		Name:        name,
	}, nil
}
