// Code generated by apps/backend/scripts/generate-web-project-members.mjs from openapi/opentoggl-web.openapi.json; DO NOT EDIT.

package httpapp

import (
	"context"
	"errors"
	"net/http"

	"github.com/labstack/echo/v4"
)

var errGeneratedWebProjectMembersBadRequest = errors.New("generated web project members bad request")

type GrantProjectMemberRequestBody struct {
	MemberID int64   `json:"member_id"`
	Role     *string `json:"role,omitempty"`
}

type GeneratedWebProjectMembersHandler interface {
	ListProjectMembers(context.Context, string, int64) WebResponse
	GrantProjectMember(context.Context, string, int64, GrantProjectMemberRequestBody) WebResponse
	RevokeProjectMember(context.Context, string, int64, int64) WebResponse
}

func registerGeneratedWebProjectMembersRoutes(
	server *echo.Echo,
	handler GeneratedWebProjectMembersHandler,
) {
	if handler == nil {
		return
	}

	server.GET("/web/v1/projects/:project_id/members", func(context echo.Context) error {
		projectID, ok := parsePathID(context, "project_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.ListProjectMembers(context.Request().Context(), sessionID(context), projectID)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.POST("/web/v1/projects/:project_id/members", func(context echo.Context) error {
		projectID, ok := parsePathID(context, "project_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		request, err := decodeGrantProjectMemberRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.GrantProjectMember(context.Request().Context(), sessionID(context), projectID, request)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.DELETE("/web/v1/projects/:project_id/members/:member_id", func(context echo.Context) error {
		projectID, ok := parsePathID(context, "project_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		memberID, ok := parsePathID(context, "member_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.RevokeProjectMember(context.Request().Context(), sessionID(context), projectID, memberID)
		return noContentOrJSON(context, response.StatusCode, response.Body)
	})
}

func decodeGrantProjectMemberRequest(request *http.Request) (GrantProjectMemberRequestBody, error) {
	type grantProjectMemberRequestBodyRaw struct {
		MemberID *int64  `json:"member_id"`
		Role     *string `json:"role"`
	}

	var raw grantProjectMemberRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return GrantProjectMemberRequestBody{}, err
	}
	if raw.MemberID == nil {
		return GrantProjectMemberRequestBody{}, errGeneratedWebProjectMembersBadRequest
	}

	return GrantProjectMemberRequestBody{
		MemberID: *raw.MemberID,
		Role:     raw.Role,
	}, nil
}
