// Code generated by apps/backend/scripts/generate-web-organization-settings.mjs from openapi/opentoggl-web.openapi.json; DO NOT EDIT.

package httpapp

import (
	"context"
	"errors"
	"net/http"

	"github.com/labstack/echo/v4"
)

var errGeneratedWebOrganizationSettingsBadRequest = errors.New("generated web organization settings bad request")

type UpdateOrganizationSettingsRequestBody struct {
	Name string `json:"name"`
}

type UpdateOrganizationSettingsEnvelopeRequestBody struct {
	Organization *UpdateOrganizationSettingsRequestBody `json:"organization,omitempty"`
}

type GeneratedWebOrganizationSettingsHandler interface {
	GetOrganizationSettings(context.Context, string, int64) WebResponse
	UpdateOrganizationSettings(context.Context, string, int64, UpdateOrganizationSettingsEnvelopeRequestBody) WebResponse
}

func registerGeneratedWebOrganizationSettingsRoutes(
	server *echo.Echo,
	handler GeneratedWebOrganizationSettingsHandler,
) {
	if handler == nil {
		return
	}

	server.GET("/web/v1/organizations/:organization_id/settings", func(context echo.Context) error {
		organizationID, ok := parsePathID(context, "organization_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.GetOrganizationSettings(context.Request().Context(), sessionID(context), organizationID)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.PATCH("/web/v1/organizations/:organization_id/settings", func(context echo.Context) error {
		organizationID, ok := parsePathID(context, "organization_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		request, err := decodeUpdateOrganizationSettingsRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.UpdateOrganizationSettings(context.Request().Context(), sessionID(context), organizationID, request)
		return context.JSON(response.StatusCode, response.Body)
	})
}

func decodeUpdateOrganizationSettingsRequest(request *http.Request) (UpdateOrganizationSettingsEnvelopeRequestBody, error) {
	type updateOrganizationSettingsRequestBodyRaw struct {
		Name *string `json:"name"`
	}

	type updateOrganizationSettingsEnvelopeRequestBodyRaw struct {
		Organization *updateOrganizationSettingsRequestBodyRaw `json:"organization"`
	}

	var raw updateOrganizationSettingsEnvelopeRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return UpdateOrganizationSettingsEnvelopeRequestBody{}, err
	}
	if raw.Organization == nil || raw.Organization.Name == nil {
		return UpdateOrganizationSettingsEnvelopeRequestBody{}, errGeneratedWebOrganizationSettingsBadRequest
	}

	return UpdateOrganizationSettingsEnvelopeRequestBody{
		Organization: &UpdateOrganizationSettingsRequestBody{
			Name: *raw.Organization.Name,
		},
	}, nil
}
