// Code generated by apps/backend/scripts/generate-web-profile-preferences.mjs from openapi/opentoggl-web.openapi.json; DO NOT EDIT.

package httpapp

import (
	"context"
	"errors"
	"net/http"
	"net/mail"
	"strings"

	"github.com/labstack/echo/v4"
)

var errGeneratedWebProfilePreferencesBadRequest = errors.New("generated web profile preferences bad request")

type UpdateCurrentUserProfileRequestBody struct {
	Email              string  `json:"email"`
	Fullname           string  `json:"fullname"`
	Timezone           string  `json:"timezone"`
	BeginningOfWeek    int     `json:"beginning_of_week"`
	CountryID          int64   `json:"country_id"`
	DefaultWorkspaceID int64   `json:"default_workspace_id"`
	CurrentPassword    *string `json:"current_password,omitempty"`
	Password           *string `json:"password,omitempty"`
}

type UpdateCurrentUserPreferencesRequestBody struct {
	DateFormat          *string `json:"date_format,omitempty"`
	TimeOfDayFormat     *string `json:"timeofday_format,omitempty"`
	DurationFormat      *string `json:"duration_format,omitempty"`
	PGTimeZoneName      *string `json:"pg_time_zone_name,omitempty"`
	BeginningOfWeek     *int    `json:"beginningOfWeek,omitempty"`
	CollapseTimeEntries *bool   `json:"collapseTimeEntries,omitempty"`
	LanguageCode        *string `json:"language_code,omitempty"`
	HideSidebarRight    *bool   `json:"hide_sidebar_right,omitempty"`
	ReportsCollapse     *bool   `json:"reports_collapse,omitempty"`
	ManualMode          *bool   `json:"manualMode,omitempty"`
	ManualEntryMode     *string `json:"manualEntryMode,omitempty"`
}

type GeneratedWebProfilePreferencesHandler interface {
	GetCurrentUserProfile(context.Context, string) WebResponse
	UpdateCurrentUserProfile(context.Context, string, UpdateCurrentUserProfileRequestBody) WebResponse
	ResetCurrentUserAPIToken(context.Context, string) WebResponse
	GetCurrentUserPreferences(context.Context, string) WebResponse
	UpdateCurrentUserPreferences(context.Context, string, UpdateCurrentUserPreferencesRequestBody) WebResponse
}

func registerGeneratedWebProfilePreferencesRoutes(
	server *echo.Echo,
	handler GeneratedWebProfilePreferencesHandler,
) {
	if handler == nil {
		return
	}

	server.GET("/web/v1/profile", func(context echo.Context) error {
		response := handler.GetCurrentUserProfile(context.Request().Context(), sessionID(context))
		return context.JSON(response.StatusCode, response.Body)
	})

	server.PATCH("/web/v1/profile", func(context echo.Context) error {
		request, err := decodeUpdateCurrentUserProfileRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.UpdateCurrentUserProfile(context.Request().Context(), sessionID(context), request)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.POST("/web/v1/profile/api-token/reset", func(context echo.Context) error {
		response := handler.ResetCurrentUserAPIToken(context.Request().Context(), sessionID(context))
		return context.JSON(response.StatusCode, response.Body)
	})

	server.GET("/web/v1/preferences", func(context echo.Context) error {
		response := handler.GetCurrentUserPreferences(context.Request().Context(), sessionID(context))
		return context.JSON(response.StatusCode, response.Body)
	})

	server.PATCH("/web/v1/preferences", func(context echo.Context) error {
		request, err := decodeUpdateCurrentUserPreferencesRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.UpdateCurrentUserPreferences(context.Request().Context(), sessionID(context), request)
		return context.JSON(response.StatusCode, response.Body)
	})
}

func decodeUpdateCurrentUserProfileRequest(request *http.Request) (UpdateCurrentUserProfileRequestBody, error) {
	type updateCurrentUserProfileRequestBodyRaw struct {
		Email              *string `json:"email"`
		Fullname           *string `json:"fullname"`
		Timezone           *string `json:"timezone"`
		BeginningOfWeek    *int    `json:"beginning_of_week"`
		CountryID          *int64  `json:"country_id"`
		DefaultWorkspaceID *int64  `json:"default_workspace_id"`
		CurrentPassword    *string `json:"current_password"`
		Password           *string `json:"password"`
	}

	var raw updateCurrentUserProfileRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return UpdateCurrentUserProfileRequestBody{}, err
	}
	if raw.Email == nil || raw.Fullname == nil || raw.Timezone == nil || raw.BeginningOfWeek == nil || raw.CountryID == nil || raw.DefaultWorkspaceID == nil {
		return UpdateCurrentUserProfileRequestBody{}, errGeneratedWebProfilePreferencesBadRequest
	}

	email := strings.TrimSpace(*raw.Email)
	if !generatedWebProfilePreferencesEmail(email) {
		return UpdateCurrentUserProfileRequestBody{}, errGeneratedWebProfilePreferencesBadRequest
	}

	return UpdateCurrentUserProfileRequestBody{
		Email:              email,
		Fullname:           *raw.Fullname,
		Timezone:           *raw.Timezone,
		BeginningOfWeek:    *raw.BeginningOfWeek,
		CountryID:          *raw.CountryID,
		DefaultWorkspaceID: *raw.DefaultWorkspaceID,
		CurrentPassword:    raw.CurrentPassword,
		Password:           raw.Password,
	}, nil
}

func decodeUpdateCurrentUserPreferencesRequest(request *http.Request) (UpdateCurrentUserPreferencesRequestBody, error) {
	type updateCurrentUserPreferencesRequestBodyRaw struct {
		DateFormat          *string `json:"date_format"`
		TimeOfDayFormat     *string `json:"timeofday_format"`
		DurationFormat      *string `json:"duration_format"`
		PGTimeZoneName      *string `json:"pg_time_zone_name"`
		BeginningOfWeek     *int    `json:"beginningOfWeek"`
		CollapseTimeEntries *bool   `json:"collapseTimeEntries"`
		LanguageCode        *string `json:"language_code"`
		HideSidebarRight    *bool   `json:"hide_sidebar_right"`
		ReportsCollapse     *bool   `json:"reports_collapse"`
		ManualMode          *bool   `json:"manualMode"`
		ManualEntryMode     *string `json:"manualEntryMode"`
	}

	var raw updateCurrentUserPreferencesRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return UpdateCurrentUserPreferencesRequestBody{}, err
	}

	return UpdateCurrentUserPreferencesRequestBody{
		DateFormat:          raw.DateFormat,
		TimeOfDayFormat:     raw.TimeOfDayFormat,
		DurationFormat:      raw.DurationFormat,
		PGTimeZoneName:      raw.PGTimeZoneName,
		BeginningOfWeek:     raw.BeginningOfWeek,
		CollapseTimeEntries: raw.CollapseTimeEntries,
		LanguageCode:        raw.LanguageCode,
		HideSidebarRight:    raw.HideSidebarRight,
		ReportsCollapse:     raw.ReportsCollapse,
		ManualMode:          raw.ManualMode,
		ManualEntryMode:     raw.ManualEntryMode,
	}, nil
}

func generatedWebProfilePreferencesEmail(value string) bool {
	if value == "" {
		return false
	}
	address, err := mail.ParseAddress(value)
	if err != nil {
		return false
	}
	return address.Address == value
}
