// Code generated by apps/backend/scripts/generate-web-capabilities-quota.mjs from openapi/opentoggl-web.openapi.json; DO NOT EDIT.

package httpapp

import (
	"context"
	"net/http"

	"github.com/labstack/echo/v4"
)

type GeneratedWebCapabilitiesQuotaHandler interface {
	GetWorkspaceCapabilities(context.Context, string, int64) WebResponse
	GetWorkspaceQuota(context.Context, string, int64) WebResponse
}

func registerGeneratedWebCapabilitiesQuotaRoutes(
	server *echo.Echo,
	handler GeneratedWebCapabilitiesQuotaHandler,
) {
	if handler == nil {
		return
	}

	server.GET("/web/v1/workspaces/:workspace_id/capabilities", func(context echo.Context) error {
		workspaceID, ok := parsePathID(context, "workspace_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.GetWorkspaceCapabilities(context.Request().Context(), sessionID(context), workspaceID)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.GET("/web/v1/workspaces/:workspace_id/quota", func(context echo.Context) error {
		workspaceID, ok := parsePathID(context, "workspace_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.GetWorkspaceQuota(context.Request().Context(), sessionID(context), workspaceID)
		if response.StatusCode == http.StatusOK {
			setQuotaWindowHeaders(context, response.Body)
		}
		return context.JSON(response.StatusCode, response.Body)
	})
}
