// Code generated by apps/backend/scripts/generate-web-auth-session.mjs from openapi/opentoggl-web.openapi.json; DO NOT EDIT.

package httpapp

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/mail"
	"strings"

	"github.com/labstack/echo/v4"
)

var errGeneratedWebAuthSessionBadRequest = errors.New("generated web auth session bad request")

type RegisterWebUserRequestBody struct {
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Fullname *string `json:"fullname,omitempty"`
}

type LoginWebUserRequestBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type GeneratedWebAuthSessionHandler interface {
	RegisterWebUser(context.Context, RegisterWebUserRequestBody) WebResponse
	LoginWebUser(context.Context, LoginWebUserRequestBody) WebResponse
	LogoutWebUser(context.Context, string) WebResponse
	GetWebSession(context.Context, string) WebResponse
}

func registerGeneratedWebAuthSessionRoutes(
	server *echo.Echo,
	handler GeneratedWebAuthSessionHandler,
) {
	if handler == nil {
		return
	}

	server.POST("/web/v1/auth/register", func(context echo.Context) error {
		request, err := decodeRegisterWebUserRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.RegisterWebUser(context.Request().Context(), request)
		setSessionCookie(context, response.SessionID, response.StatusCode)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.POST("/web/v1/auth/login", func(context echo.Context) error {
		request, err := decodeLoginWebUserRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.LoginWebUser(context.Request().Context(), request)
		setSessionCookie(context, response.SessionID, response.StatusCode)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.POST("/web/v1/auth/logout", func(context echo.Context) error {
		response := handler.LogoutWebUser(context.Request().Context(), sessionID(context))
		clearSessionCookie(context)
		return noContentOrJSON(context, response.StatusCode, response.Body)
	})

	server.GET("/web/v1/session", func(context echo.Context) error {
		response := handler.GetWebSession(context.Request().Context(), sessionID(context))
		return context.JSON(response.StatusCode, response.Body)
	})
}

func decodeRegisterWebUserRequest(request *http.Request) (RegisterWebUserRequestBody, error) {
	type registerWebUserRequestBodyRaw struct {
		Email    *string `json:"email"`
		Password *string `json:"password"`
		Fullname *string `json:"fullname"`
	}

	var raw registerWebUserRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return RegisterWebUserRequestBody{}, err
	}
	if raw.Email == nil || raw.Password == nil {
		return RegisterWebUserRequestBody{}, errGeneratedWebAuthSessionBadRequest
	}

	email := strings.TrimSpace(*raw.Email)
	if !generatedWebAuthSessionEmail(email) {
		return RegisterWebUserRequestBody{}, errGeneratedWebAuthSessionBadRequest
	}

	return RegisterWebUserRequestBody{
		Email:    email,
		Password: *raw.Password,
		Fullname: raw.Fullname,
	}, nil
}

func decodeLoginWebUserRequest(request *http.Request) (LoginWebUserRequestBody, error) {
	type loginWebUserRequestBodyRaw struct {
		Email    *string `json:"email"`
		Password *string `json:"password"`
	}

	var raw loginWebUserRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return LoginWebUserRequestBody{}, err
	}
	if raw.Email == nil || raw.Password == nil {
		return LoginWebUserRequestBody{}, errGeneratedWebAuthSessionBadRequest
	}

	email := strings.TrimSpace(*raw.Email)
	if !generatedWebAuthSessionEmail(email) {
		return LoginWebUserRequestBody{}, errGeneratedWebAuthSessionBadRequest
	}

	return LoginWebUserRequestBody{
		Email:    email,
		Password: *raw.Password,
	}, nil
}

func decodeGeneratedJSONBody(source io.Reader, target any) error {
	decoder := json.NewDecoder(source)
	if err := decoder.Decode(target); err != nil {
		return err
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		if err == nil {
			return errGeneratedWebAuthSessionBadRequest
		}
		return err
	}
	return nil
}

func generatedWebAuthSessionEmail(value string) bool {
	if value == "" {
		return false
	}
	address, err := mail.ParseAddress(value)
	if err != nil {
		return false
	}
	return address.Address == value
}
