// Code generated by apps/backend/scripts/generate-web-workspace-members.mjs from openapi/opentoggl-web.openapi.json; DO NOT EDIT.

package httpapp

import (
	"context"
	"errors"
	"net/http"
	"net/mail"
	"strings"

	"github.com/labstack/echo/v4"
)

var errGeneratedWebWorkspaceMembersBadRequest = errors.New("generated web workspace members bad request")

type InviteWorkspaceMemberRequestBody struct {
	Email string  `json:"email"`
	Role  *string `json:"role,omitempty"`
}

type GeneratedWebWorkspaceMembersHandler interface {
	ListWorkspaceMembers(context.Context, string, int64) WebResponse
	InviteWorkspaceMember(context.Context, string, int64, InviteWorkspaceMemberRequestBody) WebResponse
}

func registerGeneratedWebWorkspaceMembersRoutes(
	server *echo.Echo,
	handler GeneratedWebWorkspaceMembersHandler,
) {
	if handler == nil {
		return
	}

	server.GET("/web/v1/workspaces/:workspace_id/members", func(context echo.Context) error {
		workspaceID, ok := parsePathID(context, "workspace_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.ListWorkspaceMembers(context.Request().Context(), sessionID(context), workspaceID)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.POST("/web/v1/workspaces/:workspace_id/members/invitations", func(context echo.Context) error {
		workspaceID, ok := parsePathID(context, "workspace_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		request, err := decodeInviteWorkspaceMemberRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.InviteWorkspaceMember(context.Request().Context(), sessionID(context), workspaceID, request)
		return context.JSON(response.StatusCode, response.Body)
	})
}

func decodeInviteWorkspaceMemberRequest(request *http.Request) (InviteWorkspaceMemberRequestBody, error) {
	type inviteWorkspaceMemberRequestBodyRaw struct {
		Email *string `json:"email"`
		Role  *string `json:"role"`
	}

	var raw inviteWorkspaceMemberRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return InviteWorkspaceMemberRequestBody{}, err
	}
	if raw.Email == nil {
		return InviteWorkspaceMemberRequestBody{}, errGeneratedWebWorkspaceMembersBadRequest
	}

	email := strings.TrimSpace(*raw.Email)
	if !generatedWebWorkspaceMembersEmail(email) {
		return InviteWorkspaceMemberRequestBody{}, errGeneratedWebWorkspaceMembersBadRequest
	}

	return InviteWorkspaceMemberRequestBody{
		Email: email,
		Role:  raw.Role,
	}, nil
}

func generatedWebWorkspaceMembersEmail(value string) bool {
	if value == "" {
		return false
	}
	address, err := mail.ParseAddress(value)
	if err != nil {
		return false
	}
	return address.Address == value
}
