// Code generated by apps/backend/scripts/generate-web-workspace-settings.mjs from openapi/opentoggl-web.openapi.json; DO NOT EDIT.

package httpapp

import (
	"context"
	"errors"
	"net/http"

	"github.com/labstack/echo/v4"
)

var errGeneratedWebWorkspaceSettingsBadRequest = errors.New("generated web workspace settings bad request")

type UpdateWorkspaceSettingsRequestBody struct {
	Name                        string  `json:"name"`
	DefaultCurrency             string  `json:"default_currency"`
	DefaultHourlyRate           float64 `json:"default_hourly_rate"`
	Rounding                    int     `json:"rounding"`
	RoundingMinutes             int     `json:"rounding_minutes"`
	ReportsCollapse             bool    `json:"reports_collapse"`
	OnlyAdminsMayCreateProjects bool    `json:"only_admins_may_create_projects"`
	OnlyAdminsMayCreateTags     bool    `json:"only_admins_may_create_tags"`
	OnlyAdminsSeeTeamDashboard  bool    `json:"only_admins_see_team_dashboard"`
	ProjectsBillableByDefault   bool    `json:"projects_billable_by_default"`
	ProjectsPrivateByDefault    bool    `json:"projects_private_by_default"`
	ProjectsEnforceBillable     bool    `json:"projects_enforce_billable"`
	LimitPublicProjectData      bool    `json:"limit_public_project_data"`
}

type WorkspacePreferencesRequestBody struct {
	HideStartEndTimes bool   `json:"hide_start_end_times"`
	ReportLockedAt    string `json:"report_locked_at"`
}

type UpdateWorkspaceSettingsEnvelopeRequestBody struct {
	Workspace   *UpdateWorkspaceSettingsRequestBody `json:"workspace,omitempty"`
	Preferences *WorkspacePreferencesRequestBody    `json:"preferences,omitempty"`
}

type GeneratedWebWorkspaceSettingsHandler interface {
	GetWorkspaceSettings(context.Context, string, int64) WebResponse
	UpdateWorkspaceSettings(context.Context, string, int64, UpdateWorkspaceSettingsEnvelopeRequestBody) WebResponse
}

func registerGeneratedWebWorkspaceSettingsRoutes(
	server *echo.Echo,
	handler GeneratedWebWorkspaceSettingsHandler,
) {
	if handler == nil {
		return
	}

	server.GET("/web/v1/workspaces/:workspace_id/settings", func(context echo.Context) error {
		workspaceID, ok := parsePathID(context, "workspace_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.GetWorkspaceSettings(context.Request().Context(), sessionID(context), workspaceID)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.PATCH("/web/v1/workspaces/:workspace_id/settings", func(context echo.Context) error {
		workspaceID, ok := parsePathID(context, "workspace_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		request, err := decodeUpdateWorkspaceSettingsRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.UpdateWorkspaceSettings(context.Request().Context(), sessionID(context), workspaceID, request)
		return context.JSON(response.StatusCode, response.Body)
	})
}

func decodeUpdateWorkspaceSettingsRequest(request *http.Request) (UpdateWorkspaceSettingsEnvelopeRequestBody, error) {
	type updateWorkspaceSettingsRequestBodyRaw struct {
		Name                        *string  `json:"name"`
		DefaultCurrency             *string  `json:"default_currency"`
		DefaultHourlyRate           *float64 `json:"default_hourly_rate"`
		Rounding                    *int     `json:"rounding"`
		RoundingMinutes             *int     `json:"rounding_minutes"`
		ReportsCollapse             *bool    `json:"reports_collapse"`
		OnlyAdminsMayCreateProjects *bool    `json:"only_admins_may_create_projects"`
		OnlyAdminsMayCreateTags     *bool    `json:"only_admins_may_create_tags"`
		OnlyAdminsSeeTeamDashboard  *bool    `json:"only_admins_see_team_dashboard"`
		ProjectsBillableByDefault   *bool    `json:"projects_billable_by_default"`
		ProjectsPrivateByDefault    *bool    `json:"projects_private_by_default"`
		ProjectsEnforceBillable     *bool    `json:"projects_enforce_billable"`
		LimitPublicProjectData      *bool    `json:"limit_public_project_data"`
	}

	type workspacePreferencesRequestBodyRaw struct {
		HideStartEndTimes *bool   `json:"hide_start_end_times"`
		ReportLockedAt    *string `json:"report_locked_at"`
	}

	type updateWorkspaceSettingsEnvelopeRequestBodyRaw struct {
		Workspace   *updateWorkspaceSettingsRequestBodyRaw `json:"workspace"`
		Preferences *workspacePreferencesRequestBodyRaw    `json:"preferences"`
	}

	var raw updateWorkspaceSettingsEnvelopeRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return UpdateWorkspaceSettingsEnvelopeRequestBody{}, err
	}

	decoded := UpdateWorkspaceSettingsEnvelopeRequestBody{}
	if raw.Workspace != nil {
		workspace := raw.Workspace
		if workspace.Name == nil ||
			workspace.DefaultCurrency == nil ||
			workspace.DefaultHourlyRate == nil ||
			workspace.Rounding == nil ||
			workspace.RoundingMinutes == nil ||
			workspace.ReportsCollapse == nil ||
			workspace.OnlyAdminsMayCreateProjects == nil ||
			workspace.OnlyAdminsMayCreateTags == nil ||
			workspace.OnlyAdminsSeeTeamDashboard == nil ||
			workspace.ProjectsBillableByDefault == nil ||
			workspace.ProjectsPrivateByDefault == nil ||
			workspace.ProjectsEnforceBillable == nil ||
			workspace.LimitPublicProjectData == nil {
			return UpdateWorkspaceSettingsEnvelopeRequestBody{}, errGeneratedWebWorkspaceSettingsBadRequest
		}
		decoded.Workspace = &UpdateWorkspaceSettingsRequestBody{
			Name:                        *workspace.Name,
			DefaultCurrency:             *workspace.DefaultCurrency,
			DefaultHourlyRate:           *workspace.DefaultHourlyRate,
			Rounding:                    *workspace.Rounding,
			RoundingMinutes:             *workspace.RoundingMinutes,
			ReportsCollapse:             *workspace.ReportsCollapse,
			OnlyAdminsMayCreateProjects: *workspace.OnlyAdminsMayCreateProjects,
			OnlyAdminsMayCreateTags:     *workspace.OnlyAdminsMayCreateTags,
			OnlyAdminsSeeTeamDashboard:  *workspace.OnlyAdminsSeeTeamDashboard,
			ProjectsBillableByDefault:   *workspace.ProjectsBillableByDefault,
			ProjectsPrivateByDefault:    *workspace.ProjectsPrivateByDefault,
			ProjectsEnforceBillable:     *workspace.ProjectsEnforceBillable,
			LimitPublicProjectData:      *workspace.LimitPublicProjectData,
		}
	}

	if raw.Preferences != nil {
		preferences := raw.Preferences
		if preferences.HideStartEndTimes == nil || preferences.ReportLockedAt == nil {
			return UpdateWorkspaceSettingsEnvelopeRequestBody{}, errGeneratedWebWorkspaceSettingsBadRequest
		}
		decoded.Preferences = &WorkspacePreferencesRequestBody{
			HideStartEndTimes: *preferences.HideStartEndTimes,
			ReportLockedAt:    *preferences.ReportLockedAt,
		}
	}

	return decoded, nil
}
