// Code generated by apps/backend/scripts/generate-web-workspace-permissions.mjs from openapi/opentoggl-web.openapi.json; DO NOT EDIT.

package httpapp

import (
	"context"
	"errors"
	"net/http"

	"github.com/labstack/echo/v4"
)

var errGeneratedWebWorkspacePermissionsBadRequest = errors.New("generated web workspace permissions bad request")

type UpdateWorkspacePermissionsRequestBody struct {
	OnlyAdminsMayCreateProjects bool `json:"only_admins_may_create_projects"`
	OnlyAdminsMayCreateTags     bool `json:"only_admins_may_create_tags"`
	OnlyAdminsSeeTeamDashboard  bool `json:"only_admins_see_team_dashboard"`
	LimitPublicProjectData      bool `json:"limit_public_project_data"`
}

type GeneratedWebWorkspacePermissionsHandler interface {
	GetWorkspacePermissions(context.Context, string, int64) WebResponse
	UpdateWorkspacePermissions(context.Context, string, int64, UpdateWorkspacePermissionsRequestBody) WebResponse
}

func registerGeneratedWebWorkspacePermissionsRoutes(
	server *echo.Echo,
	handler GeneratedWebWorkspacePermissionsHandler,
) {
	if handler == nil {
		return
	}

	server.GET("/web/v1/workspaces/:workspace_id/permissions", func(context echo.Context) error {
		workspaceID, ok := parsePathID(context, "workspace_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.GetWorkspacePermissions(context.Request().Context(), sessionID(context), workspaceID)
		return context.JSON(response.StatusCode, response.Body)
	})

	server.PATCH("/web/v1/workspaces/:workspace_id/permissions", func(context echo.Context) error {
		workspaceID, ok := parsePathID(context, "workspace_id")
		if !ok {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		request, err := decodeUpdateWorkspacePermissionsRequest(context.Request())
		if err != nil {
			return context.JSON(http.StatusBadRequest, "Bad Request")
		}
		response := handler.UpdateWorkspacePermissions(context.Request().Context(), sessionID(context), workspaceID, request)
		return context.JSON(response.StatusCode, response.Body)
	})
}

func decodeUpdateWorkspacePermissionsRequest(request *http.Request) (UpdateWorkspacePermissionsRequestBody, error) {
	type updateWorkspacePermissionsRequestBodyRaw struct {
		OnlyAdminsMayCreateProjects *bool `json:"only_admins_may_create_projects"`
		OnlyAdminsMayCreateTags     *bool `json:"only_admins_may_create_tags"`
		OnlyAdminsSeeTeamDashboard  *bool `json:"only_admins_see_team_dashboard"`
		LimitPublicProjectData      *bool `json:"limit_public_project_data"`
	}

	var raw updateWorkspacePermissionsRequestBodyRaw
	if err := decodeGeneratedJSONBody(request.Body, &raw); err != nil {
		return UpdateWorkspacePermissionsRequestBody{}, err
	}
	if raw.OnlyAdminsMayCreateProjects == nil || raw.OnlyAdminsMayCreateTags == nil || raw.OnlyAdminsSeeTeamDashboard == nil || raw.LimitPublicProjectData == nil {
		return UpdateWorkspacePermissionsRequestBody{}, errGeneratedWebWorkspacePermissionsBadRequest
	}

	return UpdateWorkspacePermissionsRequestBody{
		OnlyAdminsMayCreateProjects: *raw.OnlyAdminsMayCreateProjects,
		OnlyAdminsMayCreateTags:     *raw.OnlyAdminsMayCreateTags,
		OnlyAdminsSeeTeamDashboard:  *raw.OnlyAdminsSeeTeamDashboard,
		LimitPublicProjectData:      *raw.LimitPublicProjectData,
	}, nil
}
